GULPEASE_TOOL = ./Gulpease.py

all :
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Analisi\ Dei\ Requisiti
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Definizione\ di\ Prodotto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Glossario
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Piano\ Di\ Progetto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Piano\ di\ Qualifica
	$(GULPEASE_TOOL) ../../2\ -\ RP/Interni/Norme\ di\ progetto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Interni/Studio\ fattibilità