GULPEASE_TOOL = ./Gulpease.py

rr:
	$(GULPEASE_TOOL) ../../1\ -\ RR/Esterni/Analisi\ Dei\ Requisiti
	$(GULPEASE_TOOL) ../../1\ -\ RR/Esterni/Glossario
	$(GULPEASE_TOOL) ../../1\ -\ RR/Esterni/Piano\ Di\ Progetto
	$(GULPEASE_TOOL) ../../1\ -\ RR/Esterni/Piano\ di\ Qualifica
	$(GULPEASE_TOOL) ../../1\ -\ RR/Interni/Studio\ fattibilità	
	$(GULPEASE_TOOL) ../../1\ -\ RR/Interni/Norme\ di\ progetto	
	$(GULPEASE_TOOL) ../../1\ -\ RR/Interni/Verbali/verbale20161223.tex

rp :
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Analisi\ Dei\ Requisiti
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Definizione\ di\ Prodotto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Glossario
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Piano\ Di\ Progetto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Piano\ di\ Qualifica
	$(GULPEASE_TOOL) ../../2\ -\ RP/Interni/Norme\ di\ progetto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Interni/Studio\ fattibilità
