GULPEASE_TOOL = ./Gulpease.py

rr:
	$(GULPEASE_TOOL) ../../1\ -\ RR/Esterni/Analisi\ Dei\ Requisiti
	$(GULPEASE_TOOL) ../../1\ -\ RR/Esterni/Glossario
	$(GULPEASE_TOOL) ../../1\ -\ RR/Esterni/Piano\ Di\ Progetto
	$(GULPEASE_TOOL) ../../1\ -\ RR/Esterni/Piano\ di\ Qualifica
	$(GULPEASE_TOOL) ../../1\ -\ RR/Interni/Studio\ fattibilità	
	$(GULPEASE_TOOL) ../../1\ -\ RR/Interni/Norme\ di\ progetto	
	$(GULPEASE_TOOL) ../../1\ -\ RR/Interni/Verbali/verbale20161223.tex

rp :
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Analisi\ Dei\ Requisiti
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Definizione\ di\ Prodotto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Glossario
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Piano\ Di\ Progetto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Esterni/Piano\ di\ Qualifica
	$(GULPEASE_TOOL) ../../2\ -\ RP/Interni/Norme\ di\ progetto
	$(GULPEASE_TOOL) ../../2\ -\ RP/Interni/Studio\ fattibilità
rq :
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Esterni/Analisi\ Dei\ Requisiti
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Esterni/Definizione\ di\ Prodotto
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Esterni/Glossario
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Esterni/Piano\ Di\ Progetto
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Esterni/Piano\ di\ Qualifica
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Interni/Norme\ di\ progetto
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Esterni/Manuale\ Utente\ -\ BringIt
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Esterni/Manuale\ Utente\ -\ Monolith
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Interni/Verbali/Esterni/Verbale_Esterno_10_20170503
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Interni/Verbali/Interni/Verbale_Interno_7_20170327
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Interni/Verbali/Interni/Verbale_Interno_8_20170402
	$(GULPEASE_TOOL) ../../3\ -\ RQ/Interni/Verbali/Interni/Verbale_Interno_9_20170407
