PARSER = ../../../../Tools/glossary/Parse.py
GENERATOR = ../../../../Tools/glossary/LocalMakeGlossary.py
CORRECTOR = ../../../../Tools/glossary/FixMarkup.py

update :
	$(PARSER) ..

fix :
	$(CORRECTOR) ..

sections :
	$(GENERATOR) ../Sections